### ISSUE TITLE
是否io优化的参数不正确

### ISSUE THREAD

**Issue by menglingwei** [orangedeng/ui-driver-aliyunecs#3]
我看目前模板里的参数为
{{input type="text" class="form-control" value=model.%%DRIVERNAME%%Config.isOptimized }}

实际的参数应该是 ioOptimized

**Comment by orangedeng** [comment]
目前aliyun driver的UI已经不在这个项目中维护，已经整合到了github.com/rancher/ui中，我会在那边提相同的issue

**Comment by menglingwei** [comment]
好的，非常感谢。如果有新的issue开出来，麻烦也发我一下。我这里跟踪一下。
